/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyResponseUnitWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class EmergencyResponseUnitAdminJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    
    
    /**
     * Creates new form EmergencyResponseUnitAdmin
     */
    public EmergencyResponseUnitAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emuAdminJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageUnits = new javax.swing.JButton();
        btnManageOrganizations = new javax.swing.JButton();
        btnManageAccounts = new javax.swing.JButton();
        emuAdminRightJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnManageUnits.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUnits.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageUnits.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUnits.setText("Manage Units");
        btnManageUnits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUnitsActionPerformed(evt);
            }
        });

        btnManageOrganizations.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrganizations.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganizations.setText("Manage Organization");
        btnManageOrganizations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationsActionPerformed(evt);
            }
        });

        btnManageAccounts.setBackground(new java.awt.Color(0, 0, 0));
        btnManageAccounts.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAccounts.setText("Manage Organization Accounts");
        btnManageAccounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnManageUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrganizations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnManageOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnManageAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        emuAdminRightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        emuAdminRightJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emuAdminJPanelLayout = new javax.swing.GroupLayout(emuAdminJPanel);
        emuAdminJPanel.setLayout(emuAdminJPanelLayout);
        emuAdminJPanelLayout.setHorizontalGroup(
            emuAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emuAdminJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emuAdminRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        emuAdminJPanelLayout.setVerticalGroup(
            emuAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emuAdminRightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(emuAdminJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationsActionPerformed
        // TODO add your handling code here:
//        manageOrganizationPanel.setBackground(new Color(236,113,107));
//        manageEmployee.setBackground(new Color(215,81,81));
//        manageUserAccount.setBackground(new Color(215,81,81));
        EmergencyManageOrganizationJPanel manageOrganizationJPanel = new EmergencyManageOrganizationJPanel(emuAdminRightJPanel, enterprise.getOrganizationDirectory(),enterprise);        
        emuAdminRightJPanel.add("manageOrganizationJPanel",manageOrganizationJPanel);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageOrganizationsActionPerformed

    private void btnManageUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUnitsActionPerformed
        // TODO add your handling code here:
//        manageEmployee.setBackground(new Color(236,113,107));
//        manageOrganizationPanel.setBackground(new Color(215,81,81));
//        manageUserAccount.setBackground(new Color(215,81,81));
        EmergencyManageEmployeeJPanel manageUnits = new EmergencyManageEmployeeJPanel(emuAdminRightJPanel, enterprise.getOrganizationDirectory());
        emuAdminRightJPanel.add("EmergencyManageEmployeeJPanel",manageUnits);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageUnitsActionPerformed

    private void btnManageAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountsActionPerformed
        // TODO add your handling code here:
//        manageUserAccount.setBackground(new Color(236,113,107));
//        manageOrganizationPanel.setBackground(new Color(215,81,81));
//        manageEmployee.setBackground(new Color(215,81,81));
        EmergencyManageUserAccountJPanel manageAccounts = new EmergencyManageUserAccountJPanel(emuAdminRightJPanel, enterprise, ecosystem);
        emuAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageAccountsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAccounts;
    private javax.swing.JButton btnManageOrganizations;
    private javax.swing.JButton btnManageUnits;
    private javax.swing.JPanel emuAdminJPanel;
    private javax.swing.JPanel emuAdminRightJPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
