/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

import userinterface.RecoveryUnitWorkArea.*;
import userinterface.MitigationUnitWorkArea.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.EmergencyResponseUnitWorkArea.*;

/**
 *
 * @author rtspi
 */
public class VolunteerAdminJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;

    /**
     * Creates new form EmergencyResponseUnitAdmin
     */
    public VolunteerAdminJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recoveryAdminJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageVolunteers = new javax.swing.JButton();
        btnManageOrganizations = new javax.swing.JButton();
        btnManageDisaster = new javax.swing.JButton();
        btnManageVolunteerAccounts = new javax.swing.JButton();
        volunteerAdminRightJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnManageVolunteers.setBackground(new java.awt.Color(0, 0, 0));
        btnManageVolunteers.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageVolunteers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageVolunteers.setText("Manage Volunteers");
        btnManageVolunteers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageVolunteers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteersActionPerformed(evt);
            }
        });

        btnManageOrganizations.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrganizations.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganizations.setText("Manage Organization");
        btnManageOrganizations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationsActionPerformed(evt);
            }
        });

        btnManageDisaster.setBackground(new java.awt.Color(0, 0, 0));
        btnManageDisaster.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageDisaster.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDisaster.setText("Manage Disaster Requests");
        btnManageDisaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageDisaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDisasterActionPerformed(evt);
            }
        });

        btnManageVolunteerAccounts.setBackground(new java.awt.Color(0, 0, 0));
        btnManageVolunteerAccounts.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageVolunteerAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageVolunteerAccounts.setText("Manage Volunteer Accounts");
        btnManageVolunteerAccounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageVolunteerAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteerAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageDisaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageVolunteers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrganizations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageVolunteerAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnManageOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageVolunteers, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnManageVolunteerAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnManageDisaster, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        volunteerAdminRightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        volunteerAdminRightJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout recoveryAdminJPanelLayout = new javax.swing.GroupLayout(recoveryAdminJPanel);
        recoveryAdminJPanel.setLayout(recoveryAdminJPanelLayout);
        recoveryAdminJPanelLayout.setHorizontalGroup(
            recoveryAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recoveryAdminJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volunteerAdminRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        recoveryAdminJPanelLayout.setVerticalGroup(
            recoveryAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(volunteerAdminRightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(recoveryAdminJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationsActionPerformed
        // TODO add your handling code here:
        ManageVolunteerOrganizationJPanel manageOrganizationJPanel = new ManageVolunteerOrganizationJPanel(volunteerAdminRightJPanel, enterprise.getOrganizationDirectory(),enterprise);        
        volunteerAdminRightJPanel.add("manageOrganizationJPanel",manageOrganizationJPanel);
        CardLayout layout = (CardLayout) volunteerAdminRightJPanel.getLayout();
        layout.next(volunteerAdminRightJPanel);
    }//GEN-LAST:event_btnManageOrganizationsActionPerformed

    private void btnManageVolunteersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteersActionPerformed
        // TODO add your handling code here:
        ManageVolunteerJPanel manageUnits = new ManageVolunteerJPanel(volunteerAdminRightJPanel, enterprise.getOrganizationDirectory());
        volunteerAdminRightJPanel.add("EmergencyManageEmployeeJPanel",manageUnits);
        CardLayout layout = (CardLayout) volunteerAdminRightJPanel.getLayout();
        layout.next(volunteerAdminRightJPanel);
    }//GEN-LAST:event_btnManageVolunteersActionPerformed

    private void btnManageDisasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDisasterActionPerformed
        // TODO add your handling code here:
        ManageVolunteerWorkArea manageDisasters = new ManageVolunteerWorkArea(volunteerAdminRightJPanel,account, enterprise, network, system);
        volunteerAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageDisasters);
        CardLayout layout = (CardLayout) volunteerAdminRightJPanel.getLayout();
        layout.next(volunteerAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageDisasterActionPerformed

    private void btnManageVolunteerAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteerAccountsActionPerformed
        // TODO add your handling code here:
        ManageVolunteerUserAccountJPanel manageAccounts = new ManageVolunteerUserAccountJPanel(volunteerAdminRightJPanel, enterprise, system);
        volunteerAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) volunteerAdminRightJPanel.getLayout();
        layout.next(volunteerAdminRightJPanel);
    }//GEN-LAST:event_btnManageVolunteerAccountsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDisaster;
    private javax.swing.JButton btnManageOrganizations;
    private javax.swing.JButton btnManageVolunteerAccounts;
    private javax.swing.JButton btnManageVolunteers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel recoveryAdminJPanel;
    private javax.swing.JPanel volunteerAdminRightJPanel;
    // End of variables declaration//GEN-END:variables
}
