/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RecoveryUnitWorkArea;

import userinterface.MitigationUnitWorkArea.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.EmergencyResponseUnitWorkArea.*;

/**
 *
 * @author rtspi
 */
public class RecoveryUnitAdminJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;

    /**
     * Creates new form EmergencyResponseUnitAdmin
     */
    public RecoveryUnitAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recoveryAdminJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageUnits = new javax.swing.JButton();
        btnManageOrganizations = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        recoveryAdminRightJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnManageUnits.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUnits.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageUnits.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUnits.setText("Manage Units");
        btnManageUnits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUnitsActionPerformed(evt);
            }
        });

        btnManageOrganizations.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrganizations.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganizations.setText("Manage Organization");
        btnManageOrganizations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationsActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Manage Organization Accounts");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrganizations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnManageOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        recoveryAdminRightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        recoveryAdminRightJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout recoveryAdminJPanelLayout = new javax.swing.GroupLayout(recoveryAdminJPanel);
        recoveryAdminJPanel.setLayout(recoveryAdminJPanelLayout);
        recoveryAdminJPanelLayout.setHorizontalGroup(
            recoveryAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recoveryAdminJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recoveryAdminRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        recoveryAdminJPanelLayout.setVerticalGroup(
            recoveryAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recoveryAdminRightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(recoveryAdminJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationsActionPerformed
        // TODO add your handling code here:
        RecoveryManageOrganizationJPanel manageOrganizationJPanel = new RecoveryManageOrganizationJPanel(recoveryAdminRightJPanel, enterprise.getOrganizationDirectory(),enterprise);        
        recoveryAdminRightJPanel.add("manageOrganizationJPanel",manageOrganizationJPanel);
        CardLayout layout = (CardLayout) recoveryAdminRightJPanel.getLayout();
        layout.next(recoveryAdminRightJPanel);
    }//GEN-LAST:event_btnManageOrganizationsActionPerformed

    private void btnManageUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUnitsActionPerformed
        // TODO add your handling code here:
        RecoveryManageEmployeeJPanel manageUnits = new RecoveryManageEmployeeJPanel(recoveryAdminRightJPanel, enterprise.getOrganizationDirectory());
        recoveryAdminRightJPanel.add("EmergencyManageEmployeeJPanel",manageUnits);
        CardLayout layout = (CardLayout) recoveryAdminRightJPanel.getLayout();
        layout.next(recoveryAdminRightJPanel);
    }//GEN-LAST:event_btnManageUnitsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RecoveryUnitManageUserAccountJPanel manageAccounts = new RecoveryUnitManageUserAccountJPanel(recoveryAdminRightJPanel, enterprise, ecosystem);
        recoveryAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) recoveryAdminRightJPanel.getLayout();
        layout.next(recoveryAdminRightJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrganizations;
    private javax.swing.JButton btnManageUnits;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel recoveryAdminJPanel;
    private javax.swing.JPanel recoveryAdminRightJPanel;
    // End of variables declaration//GEN-END:variables
}
