/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReportingAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DisasterManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MitigationUnitAdminRequest;
import Business.WorkQueue.VolunteerUnitRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mayank
 */
public class ReportingAdminManageRequestsJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Organization organization;
    Network network;
    private UserAccount account;
    /**
     * Creates new form IncidentUnitManageScene
     */
    public ReportingAdminManageRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, Organization organization, Network network,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.network = network;
        this.account = account;
        populateSceneTable();
    }
    
    private void populateSceneTable(){

        DefaultTableModel model = (DefaultTableModel) sceneTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            
            if (wr instanceof VolunteerUnitRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = wr;
                row[1] = ((VolunteerUnitRequest) wr).getSceneName();
                row[2] = ((VolunteerUnitRequest) wr).getSceneZipcode();
                //row[3] = ((VolunteerUnitRequest) wr).getSceneLocationPoint();
                row[4] = ((VolunteerUnitRequest) wr).getNoOfVictims();
                row[5] = ((VolunteerUnitRequest) wr).getEstimatedLoss();
                row[6] = ((VolunteerUnitRequest) wr).getStatus();
                row[7] = ((VolunteerUnitRequest) wr).getRequestDate();
                row[8] = ((VolunteerUnitRequest) wr).getMessage();
                model.addRow(row);
            }
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sceneTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sceneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sceneZipCode = new javax.swing.JTextField();
        noOfVictims = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estimatedLoss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createSceneBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sceneTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Scene #", "Scene Name", "Zip Code", "Location", "# of Victims", "Estimated Loss", "Status", "Created Date", "Additional Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sceneTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        sceneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sceneTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sceneTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 48, 1010, 146));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Scene Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 211, -1, -1));

        sceneName.setEditable(false);
        sceneName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneName.setForeground(new java.awt.Color(25, 56, 82));
        sceneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceneNameActionPerformed(evt);
            }
        });
        add(sceneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 188, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setText("Zip Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 254, -1, -1));

        sceneZipCode.setEditable(false);
        sceneZipCode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneZipCode.setForeground(new java.awt.Color(25, 56, 82));
        add(sceneZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 250, 190, -1));

        noOfVictims.setEditable(false);
        noOfVictims.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        noOfVictims.setForeground(new java.awt.Color(25, 56, 82));
        add(noOfVictims, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 292, 188, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("# of victims");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 297, -1, -1));

        estimatedLoss.setEditable(false);
        estimatedLoss.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        estimatedLoss.setForeground(new java.awt.Color(25, 56, 82));
        add(estimatedLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 335, 188, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 56, 82));
        jLabel5.setText("Estimated Loss");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 340, -1, -1));

        createSceneBtn.setBackground(new java.awt.Color(255, 255, 255));
        createSceneBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createSceneBtn.setForeground(new java.awt.Color(25, 56, 82));
        createSceneBtn.setText("Approve");
        createSceneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSceneBtnActionPerformed(evt);
            }
        });
        add(createSceneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 713, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 56, 82));
        jButton1.setText("Reject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 713, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 56, 82));
        jLabel8.setText("MANAGE REQUEST");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 8, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/collaboration.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sceneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sceneNameActionPerformed

    private void createSceneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSceneBtnActionPerformed
        
        int selectedRow = sceneTable.getSelectedRow();        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Scene", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Assigned Reporting Admin")){
            String msg = JOptionPane.showInputDialog("Additional Message");
        
            selectedWorkReq.setStatus("Forwarded to Disaster Team");
            selectedWorkReq.setMessage(msg);

            MitigationUnitAdminRequest sceneReq = new MitigationUnitAdminRequest();
            sceneReq.setSceneName(sceneName.getText());
            sceneReq.setSceneZipcode(sceneZipCode.getText());
            sceneReq.setNoOfVictims(Integer.parseInt(noOfVictims.getText()));
            sceneReq.setEstimatedLoss(estimatedLoss.getText());
            //sceneReq.setSceneLocationPoint(selectedWorkReq.getSceneLocationPoint());
            sceneReq.setStatus("Requested");  
            sceneReq.setSender(account);
            //sceneReq.setSceneId("S"+(organization.getWorkQueue().getWorkRequestList().size()+1));
            sceneReq.setMessage("Waiting for disaster head to approve request");

            account.getWorkQueue().getWorkRequestList().add(sceneReq);

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof DisasterManagementOrganization) {
                         o.getWorkQueue().getWorkRequestList().add(sceneReq);
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Request is Accepted successfully");
            populateSceneTable();
        }else if(selectedWorkReq.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Request is already Rejected", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Cancelled")) {
            JOptionPane.showMessageDialog(null, "Request has been cancelled by the user", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "Request is already Accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_createSceneBtnActionPerformed
    VolunteerUnitRequest selectedWorkReq;
    private void sceneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sceneTableMouseClicked
        //int selectedReq = sceneTable.rowAtPoint(evt.getPoint());
        
        int selectedReq = sceneTable.getSelectedRow();
        selectedWorkReq = (VolunteerUnitRequest)sceneTable.getValueAt(selectedReq, 0);
        sceneName.setText(selectedWorkReq.getSceneName());
        sceneZipCode.setText(selectedWorkReq.getSceneZipcode());
        noOfVictims.setText(selectedWorkReq.getNoOfVictims()+"");
        estimatedLoss.setText(selectedWorkReq.getEstimatedLoss());
        //sceneLocation.setText(selectedWorkReq.getSceneLocationPoint()+"");
        sceneName.setText(selectedWorkReq.getSceneName());
        //displayImage(selectedWorkReq.getImagePath());
        System.out.println("/********/////");
        
        
        
        
    }//GEN-LAST:event_sceneTableMouseClicked
   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int selectedRow = sceneTable.getSelectedRow();        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Scene", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Assigned Reporting Admin")){
            String msg = JOptionPane.showInputDialog("Additional Message");
            selectedWorkReq.setStatus("Rejected");
            selectedWorkReq.setMessage(msg);
            populateSceneTable();
            JOptionPane.showMessageDialog(null, "Request is Rejected successfully");
        }else if(selectedWorkReq.getStatus().equals("Forwarded to Disaster Team")){
            JOptionPane.showMessageDialog(null, "Request is already Accepted");
        }else if(selectedWorkReq.getStatus().equals("Cancelled")) {
            JOptionPane.showMessageDialog(null, "Request has been cancelled by the user", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Forwarded to Disaster Team")) {
            JOptionPane.showMessageDialog(null, "Request has already been accepted and processed", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "Request is already Rejected");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSceneBtn;
    private javax.swing.JTextField estimatedLoss;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVictims;
    private javax.swing.JTextField sceneName;
    private javax.swing.JTable sceneTable;
    private javax.swing.JTextField sceneZipCode;
    // End of variables declaration//GEN-END:variables
}
