/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReportingAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DisasterManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MitigationUnitAdminRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.MitigationUnitWorkArea.*;

/**
 *
 * @author Mayank
 */
public class ReportingAdminManageSceneJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Organization organization;
    Network network;
    private UserAccount account;
    /**
     * Creates new form IncidentUnitManageScene
     */
    public ReportingAdminManageSceneJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, Organization organization, Network network,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.network = network;
        this.account = account;
        populateSceneTable();
    }
    
    private void populateSceneTable(){
        DefaultTableModel model = (DefaultTableModel) sceneTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            
            if (wr instanceof MitigationUnitAdminRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = wr;
                row[1] = ((MitigationUnitAdminRequest) wr).getSceneName();
                row[2] = ((MitigationUnitAdminRequest) wr).getSceneZipcode();
                //row[3] = ((MitigationUnitAdminRequest) wr).getSceneLocationPoint();
                row[4] = ((MitigationUnitAdminRequest) wr).getNoOfVictims();
                row[5] = ((MitigationUnitAdminRequest) wr).getEstimatedLoss();
                row[6] = ((MitigationUnitAdminRequest) wr).getStatus();
                row[7] = ((MitigationUnitAdminRequest) wr).getRequestDate();
                row[8] = ((MitigationUnitAdminRequest) wr).getMessage();
                //row[2] = org.getPosition();
                model.addRow(row);
            }
            
            
            /*Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);*/
        }
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sceneTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sceneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sceneZipCode = new javax.swing.JTextField();
        noOfVictims = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estimatedLoss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createSceneBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sceneTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Scene #", "Scene Name", "Zip Code", "Location", "# of Victims", "Estimated Loss", "Status", "Created Date", "Additional Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sceneTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(sceneTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1010, 146));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Scene Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 297, -1, -1));

        sceneName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneName.setForeground(new java.awt.Color(25, 56, 82));
        sceneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceneNameActionPerformed(evt);
            }
        });
        add(sceneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 292, 188, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setText("Zip Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 340, -1, -1));

        sceneZipCode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneZipCode.setForeground(new java.awt.Color(25, 56, 82));
        add(sceneZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 335, 188, -1));

        noOfVictims.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        noOfVictims.setForeground(new java.awt.Color(25, 56, 82));
        add(noOfVictims, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 378, 188, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("# of victims");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 383, -1, -1));

        estimatedLoss.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        estimatedLoss.setForeground(new java.awt.Color(25, 56, 82));
        add(estimatedLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 421, 188, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 56, 82));
        jLabel5.setText("Estimated Loss");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 426, -1, -1));

        createSceneBtn.setBackground(new java.awt.Color(255, 255, 255));
        createSceneBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createSceneBtn.setForeground(new java.awt.Color(25, 56, 82));
        createSceneBtn.setText("Create Scene");
        createSceneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSceneBtnActionPerformed(evt);
            }
        });
        add(createSceneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 519, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setText("MANAGE SCENE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 21, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/emergencyServiceManager700x.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/crime128x.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sceneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sceneNameActionPerformed

    private void createSceneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSceneBtnActionPerformed
        int zipCode, victimCount, loss;

        if("".equals(sceneName.getText())){
            JOptionPane.showMessageDialog(null, "Scene Name is mandatory");
        }else if("".equals(sceneZipCode.getText())){
            JOptionPane.showMessageDialog(null, "Scene Zip Code is mandatory");
        }else if("".equals(noOfVictims.getText())){
            JOptionPane.showMessageDialog(null, "No of victims is mandatory");
        }else if("".equals(estimatedLoss.getText())){
            JOptionPane.showMessageDialog(null, "Estimated Loss is mandatory");
        }else {
            try {
                zipCode = Integer.parseInt(sceneZipCode.getText());
                victimCount = Integer.parseInt(noOfVictims.getText());
                loss = Integer.parseInt(estimatedLoss.getText());
                String msg = JOptionPane.showInputDialog("Additional Message");
                MitigationUnitAdminRequest sceneReq = new MitigationUnitAdminRequest();
                sceneReq.setSceneName(sceneName.getText());
                sceneReq.setSceneZipcode(sceneZipCode.getText());
                sceneReq.setNoOfVictims(Integer.parseInt(noOfVictims.getText()));
                sceneReq.setEstimatedLoss(estimatedLoss.getText());
                sceneReq.setStatus("Requested");
                sceneReq.setSender(account);
                //sceneReq.setSceneId("S"+(organization.getWorkQueue().getWorkRequestList().size()+1));
                //sceneReq.setMessage("Waiting for disaster head to approve request");
                sceneReq.setMessage(msg);

                account.getWorkQueue().getWorkRequestList().add(sceneReq);

                //for (Network net : business.getNetworkList()) {
                    for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            if (o instanceof DisasterManagementOrganization) {
                                o.getWorkQueue().getWorkRequestList().add(sceneReq);
                            }
                        }
                    }
                    populateSceneTable();
                    resetFields();
                    //}
            }catch(NumberFormatException exception){
                JOptionPane.showMessageDialog(null, "ZipCode, no of victimes and estimated loss need to be in integer!");
            }
        }
    }//GEN-LAST:event_createSceneBtnActionPerformed
    public void resetFields() {
        sceneName.setText("");
        sceneZipCode.setText("");
        noOfVictims.setText("");
        estimatedLoss.setText("");
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSceneBtn;
    private javax.swing.JTextField estimatedLoss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVictims;
    private javax.swing.JTextField sceneName;
    private javax.swing.JTable sceneTable;
    private javax.swing.JTextField sceneZipCode;
    // End of variables declaration//GEN-END:variables
}
