/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Network.Network;
//import Business.Utils.HeaderColors;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rtspi
 * 
 */



public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }

    private void populateNetworkTable() {
        
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NetworkManagementjLabel = new javax.swing.JLabel();
        EnterLocationjLabel = new javax.swing.JLabel();
        LocationTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        SubmitJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NetworkManagementjLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        NetworkManagementjLabel.setText("Network Management ");
        add(NetworkManagementjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 260, -1));

        EnterLocationjLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        EnterLocationjLabel.setText("Enter Location :");
        add(EnterLocationjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, -1));

        LocationTextField.setToolTipText("Enter the location");
        LocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationTextFieldActionPerformed(evt);
            }
        });
        add(LocationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, -1));

        networkJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(25, 56, 82));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        networkJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(networkJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 567, 110));

        SubmitJButton.setBackground(new java.awt.Color(0, 0, 0));
        SubmitJButton.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        SubmitJButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitJButton.setText("Submit");
        SubmitJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJButtonActionPerformed(evt);
            }
        });
        add(SubmitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 110, 40));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setText("Location Table");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/networkimage.PNG"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 750, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void LocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationTextFieldActionPerformed

    private void SubmitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJButtonActionPerformed
        // TODO add your handling code here:
        String name = LocationTextField.getText().trim();
        if(!name.isEmpty()){
            if(system.checkIfNetworkIsUnique(name)){
                Network network = system.createAndAddNetwork();
                network.setName(name);
                JOptionPane.showMessageDialog(null, "Location Added Successfully", "Success", 2);
                LocationTextField.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Network Already Exits");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Enter Location");
        }
        
        
        populateNetworkTable();
    }//GEN-LAST:event_SubmitJButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterLocationjLabel;
    private javax.swing.JTextField LocationTextField;
    private javax.swing.JLabel NetworkManagementjLabel;
    private javax.swing.JButton SubmitJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable networkJTable;
    // End of variables declaration//GEN-END:variables
}
