/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MitigationUnitWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.EmergencyResponseUnitWorkArea.*;

/**
 *
 * @author rtspi
 */
public class MitigationUnitAdminJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Organization organization;

    /**
     * Creates new form EmergencyResponseUnitAdmin
     */
    public MitigationUnitAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecosystem, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mitigationAdminJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageUnits = new javax.swing.JButton();
        btnManageOrganizations = new javax.swing.JButton();
        btnManageDisasters = new javax.swing.JButton();
        btnManageUserAccounts1 = new javax.swing.JButton();
        mitigationAdminRightJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnManageUnits.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUnits.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageUnits.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUnits.setText("Manage Units");
        btnManageUnits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUnitsActionPerformed(evt);
            }
        });

        btnManageOrganizations.setBackground(new java.awt.Color(0, 0, 0));
        btnManageOrganizations.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganizations.setText("Manage Organization");
        btnManageOrganizations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationsActionPerformed(evt);
            }
        });

        btnManageDisasters.setBackground(new java.awt.Color(0, 0, 0));
        btnManageDisasters.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageDisasters.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDisasters.setText("Manage Disasters");
        btnManageDisasters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageDisasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDisastersActionPerformed(evt);
            }
        });

        btnManageUserAccounts1.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUserAccounts1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageUserAccounts1.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUserAccounts1.setText("Manage Organization Accounts");
        btnManageUserAccounts1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageUserAccounts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccounts1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageDisasters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrganizations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUserAccounts1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnManageOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnManageUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnManageUserAccounts1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnManageDisasters, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        mitigationAdminRightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        mitigationAdminRightJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout mitigationAdminJPanelLayout = new javax.swing.GroupLayout(mitigationAdminJPanel);
        mitigationAdminJPanel.setLayout(mitigationAdminJPanelLayout);
        mitigationAdminJPanelLayout.setHorizontalGroup(
            mitigationAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mitigationAdminJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mitigationAdminRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mitigationAdminJPanelLayout.setVerticalGroup(
            mitigationAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mitigationAdminRightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(mitigationAdminJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationsActionPerformed
        // TODO add your handling code here:
        MitigationManageOrganizationJPanel manageOrganizationJPanel = new MitigationManageOrganizationJPanel(mitigationAdminRightJPanel, enterprise.getOrganizationDirectory(),enterprise);        
        mitigationAdminRightJPanel.add("manageOrganizationJPanel",manageOrganizationJPanel);
        CardLayout layout = (CardLayout) mitigationAdminRightJPanel.getLayout();
        layout.next(mitigationAdminRightJPanel);
    }//GEN-LAST:event_btnManageOrganizationsActionPerformed

    private void btnManageUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUnitsActionPerformed
        // TODO add your handling code here:
        MitigationManageEmployeeJPanel manageUnits = new MitigationManageEmployeeJPanel(mitigationAdminRightJPanel, enterprise.getOrganizationDirectory());
        mitigationAdminRightJPanel.add("EmergencyManageEmployeeJPanel",manageUnits);
        CardLayout layout = (CardLayout) mitigationAdminRightJPanel.getLayout();
        layout.next(mitigationAdminRightJPanel);
    }//GEN-LAST:event_btnManageUnitsActionPerformed

    private void btnManageDisastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDisastersActionPerformed
        // TODO add your handling code here:
        MitigationManagerSceneManageJPanel manageAccounts = new MitigationManagerSceneManageJPanel(mitigationAdminRightJPanel, enterprise, ecosystem, organization);
        mitigationAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) mitigationAdminRightJPanel.getLayout();
        layout.next(mitigationAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageDisastersActionPerformed

    private void btnManageUserAccounts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccounts1ActionPerformed
        // TODO add your handling code here:
        MitigationUnitManageUserAccountJPanel manageAccounts = new MitigationUnitManageUserAccountJPanel(mitigationAdminRightJPanel, enterprise, ecosystem);
        mitigationAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) mitigationAdminRightJPanel.getLayout();
        layout.next(mitigationAdminRightJPanel);
    }//GEN-LAST:event_btnManageUserAccounts1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDisasters;
    private javax.swing.JButton btnManageOrganizations;
    private javax.swing.JButton btnManageUnits;
    private javax.swing.JButton btnManageUserAccounts1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mitigationAdminJPanel;
    private javax.swing.JPanel mitigationAdminRightJPanel;
    // End of variables declaration//GEN-END:variables
}
