/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DisasterManagementHead;

import userinterface.EmergencyResponseUnitWorkArea.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class DisasterManagmentHeadAdminJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    UserAccount account;
    Organization org;
    Network network;
    
    /**
     * Creates new form EmergencyResponseUnitAdmin
     */
    public DisasterManagmentHeadAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, Organization organization, Network network,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = system;
        this.network = network;
        this.org = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emuAdminJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnReportDisasters = new javax.swing.JButton();
        btnManageUnits = new javax.swing.JButton();
        btnManageAccounts = new javax.swing.JButton();
        emuAdminRightJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnReportDisasters.setBackground(new java.awt.Color(0, 0, 0));
        btnReportDisasters.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnReportDisasters.setForeground(new java.awt.Color(255, 255, 255));
        btnReportDisasters.setText("Report Disasters");
        btnReportDisasters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportDisasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDisastersActionPerformed(evt);
            }
        });

        btnManageUnits.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUnits.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageUnits.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUnits.setText("Manage Units");
        btnManageUnits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUnitsActionPerformed(evt);
            }
        });

        btnManageAccounts.setBackground(new java.awt.Color(0, 0, 0));
        btnManageAccounts.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAccounts.setText("Manage User Accounts");
        btnManageAccounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnManageUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportDisasters, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnReportDisasters, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnManageUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnManageAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        emuAdminRightJPanel.setBackground(new java.awt.Color(255, 255, 255));
        emuAdminRightJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout emuAdminJPanelLayout = new javax.swing.GroupLayout(emuAdminJPanel);
        emuAdminJPanel.setLayout(emuAdminJPanelLayout);
        emuAdminJPanelLayout.setHorizontalGroup(
            emuAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emuAdminJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emuAdminRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        emuAdminJPanelLayout.setVerticalGroup(
            emuAdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emuAdminRightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(emuAdminJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportDisastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDisastersActionPerformed
        // TODO add your handling code here:
//        manageOrganizationPanel.setBackground(new Color(236,113,107));
//        manageEmployee.setBackground(new Color(215,81,81));
//        manageUserAccount.setBackground(new Color(215,81,81));
        ManageDisastersJPanel manageDisasters = new ManageDisastersJPanel(emuAdminRightJPanel, enterprise, ecosystem, org,network, account);        
        emuAdminRightJPanel.add("manageOrganizationJPanel",manageDisasters);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnReportDisastersActionPerformed

    private void btnManageUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUnitsActionPerformed
        // TODO add your handling code here:
//        manageEmployee.setBackground(new Color(236,113,107));
//        manageOrganizationPanel.setBackground(new Color(215,81,81));
//        manageUserAccount.setBackground(new Color(215,81,81));
        DisasterManageEmployeeJPanel manageUnits = new DisasterManageEmployeeJPanel(emuAdminRightJPanel, enterprise.getOrganizationDirectory());
        emuAdminRightJPanel.add("EmergencyManageEmployeeJPanel",manageUnits);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageUnitsActionPerformed

    private void btnManageAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountsActionPerformed
        // TODO add your handling code here:
//        manageUserAccount.setBackground(new Color(236,113,107));
//        manageOrganizationPanel.setBackground(new Color(215,81,81));
//        manageEmployee.setBackground(new Color(215,81,81));
        DisasterManageUserAccountJPanel manageAccounts = new DisasterManageUserAccountJPanel(emuAdminRightJPanel, enterprise, ecosystem);
        emuAdminRightJPanel.add("EmergencyManageUserAccountJPanel",manageAccounts);
        CardLayout layout = (CardLayout) emuAdminRightJPanel.getLayout();
        layout.next(emuAdminRightJPanel);
        
    }//GEN-LAST:event_btnManageAccountsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAccounts;
    private javax.swing.JButton btnManageUnits;
    private javax.swing.JButton btnReportDisasters;
    private javax.swing.JPanel emuAdminJPanel;
    private javax.swing.JPanel emuAdminRightJPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
